version: '3.3'
networks:
  signature-app:
    driver: 'bridge'
services:
  postgres:
    image: postgres:13
    restart: always
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      PGUSER: sandbox
      POSTGRES_USER: sandbox
      POSTGRES_PASSWORD: sandbox
      PGPASSWORD: sandbox
      POSTGRES_DB: signature-app
      PGDATABASE: signature-app
    networks:
      - signature-app
